const { createClient } = require('@supabase/supabase-js')
require('dotenv').config()

async function investigateDatabase() {
  console.log('🔍 Database Investigation Function Deployed!')  
  console.log('')
  console.log('⚠️  To test the database investigation, follow these steps:')
  console.log('')
  console.log('1. Go to your Echoes app in the browser and log in')
  console.log('2. Open browser dev tools (F12)')
  console.log('3. Go to Network tab and refresh the page')
  console.log('4. Find any request to Supabase and copy the Authorization header')
  console.log('5. Use the token in a request to:')
  console.log('')
  console.log('   URL: https://nwvratuzlwsdapedmqqj.supabase.co/functions/v1/test-lambda')
  console.log('   Method: POST')
  console.log('   Headers:')
  console.log('     - Authorization: Bearer YOUR_TOKEN_HERE')  
  console.log('     - Content-Type: application/json')
  console.log('')
  console.log('This will show:')
  console.log('- Total clips and status breakdown')
  console.log('- Any duplicate records')
  console.log('- Recent clips analysis')
  console.log('- Processing vs completed status issues')
  console.log('')
  console.log('🎯 This should help identify the root cause of the dashboard issues!')
}

investigateDatabase() 